In [11]:
import numpy as np;
np.arange(10,20,2);

In [15]:
x=np.array([3,5])

In [16]:
print(x)

[3 5]


In [17]:
y=np.array([1,2,3,4,5])
print(y)

[1 2 3 4 5]


In [21]:
z=np.array([8,1])
print(z)

[8 1]


In [22]:
print(np.greater(x, z))

[False  True]


In [23]:
print(np.greater_equal(x, z))

[False  True]


In [24]:
print(np.less(x, z))

[ True False]


In [25]:
print(np.less_equal(x, z))

[ True False]


In [27]:
x=np.arange(30,71,2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [28]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
x=np.arange(21)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [31]:
x[(x>=9) & (x<=15)] *= -1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [32]:
x=np.diag([1,2,3,4,5])
print(x)
          

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(np.sum(x))

10


In [5]:
print(np.sum(x,axis=0))

[4 6]


In [6]:
print(np.sum(x,axis=1))

[3 7]


In [8]:
import os
x=np.arange(12).reshape(4,3)
print("original array")
print(x)
header='col1 col2 col3'
np.savetxt('temp.txt',x,fmt="%d",header=header)
print("after loading the content of the file")
result=np.loadtxt('temp.txt')
print(result)

original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
after loading the content of the file
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [9]:
x=np.array([1,2,3,4,5])
y=np.array([1,2,4,6,5])
print(np.equal(x,y))

[ True  True False False  True]


In [10]:
nums=np.arange(16,dtype='int').reshape(-1,4)
print("original is")
print(nums)
print("after swapping last and frist digit in the array")
nums[[0,-1],:]=nums[[-1,0],:]
print(nums)

original is
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
after swapping last and frist digit in the array
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [11]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[1,2,3],[2,3,4]])
c=a*b
print(c)

[[ 1  4  9]
 [ 4  9 16]]
