In [1]:
#exercise2
#quuuestion1 
import numpy as np

In [5]:
r = int(input("Enter no. of rows"))
l1 = []
l2 = []
print("Enter the values for matrix 1\n")
for i in range(r):
    a = np.array(list(map(int, input("Enter the numbers: ").split())))
    l1.append(a)
print("\n Enter the values for matrix 2\n")
for i in range(r):
    b = np.array(list(map(int, input("Enter the numbers: ").split())))
    l2.append(b)
m1=np.matrix(l1)
m2=np.matrix(l2)
print("\n Matrix 1: \n",m1)
print("\n Matrix 2: \n",m2)

Enter no. of rows 2


Enter the values for matrix 1



Enter the numbers:  1 2
Enter the numbers:  2 4



 Enter the values for matrix 2



Enter the numbers:  5 6
Enter the numbers:  8 9



 Matrix 1: 
 [[1 2]
 [2 4]]

 Matrix 2: 
 [[5 6]
 [8 9]]


In [6]:
print("Dot Product: ")
np.dot(m1,m2)

Dot Product: 


matrix([[21, 24],
        [42, 48]])

In [7]:
#q2
print("Transpose of matrix 1 \n",np.transpose(m1),"\n\nTranspose of matrix 2\n",np.transpose(m2))

Transpose of matrix 1 
 [[1 2]
 [2 4]] 

Transpose of matrix 2
 [[5 8]
 [6 9]]


In [8]:
#q3 trace
print("Trace of matrix 1\n",np.trace(m1),"\n\nTrace of matrix 2\n",np.trace(m2))

Trace of matrix 1
 5 

Trace of matrix 2
 14


In [9]:
#4.rank
print("Rank of matrix 1\n",np.linalg.matrix_rank(m1),"\n\nRank of matrix 2\n",np.linalg.matrix_rank(m2))

Rank of matrix 1
 1 

Rank of matrix 2
 2


In [10]:
#5 determnt

print("Determinant of matrix 1\n",np.linalg.det(m1),"\n\nDeterminant of matrix 2\n",np.linalg.det(m2))

Determinant of matrix 1
 0.0 

Determinant of matrix 2
 -2.9999999999999996


In [11]:
#6inverse
if np.linalg.det(m1) != 0 :
    print("Inverse of matrix 1\n",np.linalg.inv(m1))
else:
    print("Matrix 1 is singluar \n")

if np.linalg.det(m2) != 0 :
    print("Inverse of matrix 2\n",np.linalg.inv(m2))
else:
    print("Matrix 2 is singluar ")

Matrix 1 is singluar 

Inverse of matrix 2
 [[-3.          2.        ]
 [ 2.66666667 -1.66666667]]


In [12]:
# 7. Eigen Values and Eigen Vectors
ss
print("Eigen values of matrix 1\n",np.linalg.eig(m1),"\n\nEigen values of matrix 2\n",np.linalg.eig(m2))

Eigen values of matrix 1
 (array([0., 5.]), matrix([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]])) 

Eigen values of matrix 2
 (array([-0.21110255, 14.21110255]), matrix([[-0.75499722, -0.54580557],
        [ 0.65572799, -0.83791185]]))
